-- PLEASE EXECUTE SQL SCRIPT IN initialize.sql first
-- THEN MAKE A TEST IN THIS FILE
USE TUNA_TEST;

-- Query courses
SELECT *
FROM COURSES
  LEFT JOIN TEACHERS
  ON TEACHERS.id = COURSES.teacherId
LIMIT 10;

-- Query teachers
SELECT *
FROM TEACHERS
LIMIT 10;